return {
	["Stone Ore"] = {
		Color = Color3.fromRGB(154, 170, 181),
		SellValue = 1,
	},
	["Copper Ore"] = {
		Color = Color3.fromRGB(224, 119, 74),
		SellValue = 3,
	},
	["Charged Quartz"] = {
		Color = Color3.fromRGB(84, 241, 255),
		SellValue = 7,
	},
	["Quartz Ore"] = {
		Color = Color3.fromRGB(220, 198, 255),
		SellValue = 12,
	},
	["Ion Crystal"] = {
		Color = Color3.fromRGB(195, 79, 255),
		SellValue = 22,
	},
}
