return {
	["Stone Ore"] = {
		Color = Color3.fromRGB(154, 170, 181),
		SellValue = 3,
	},
	["Copper Ore"] = {
		Color = Color3.fromRGB(224, 119, 74),
		SellValue = 6,
	},
	["Charged Quartz"] = {
		Color = Color3.fromRGB(84, 241, 255),
		SellValue = 18,
	},
	["Quartz Ore"] = {
		Color = Color3.fromRGB(220, 198, 255),
		SellValue = 50,
	},
	["Ion Crystal"] = {
		Color = Color3.fromRGB(195, 79, 255),
		SellValue = 120,
	},
	["Plasma Ore"] = { Color = Color3.fromRGB(255, 139, 54), SellValue = 350 },
	["Reactor Shard"] = { Color = Color3.fromRGB(128, 255, 98), SellValue = 1200 },
	["Fusion Ore"] = {Color = Color3.fromRGB(255, 190, 60), SellValue = 5000},
	["Antimatter Ore"] = {Color = Color3.fromRGB(255, 85, 178), SellValue = 18000},
	["Singularity Ore"] = {Color = Color3.fromRGB(140, 100, 255), SellValue = 50000},
	["Omega Ore"] = {Color = Color3.fromRGB(255, 75, 110), SellValue = 150000},
}
