return {
	["Scrap Zapper"] = {
		Id = "ScrapZapper", CardName = "StarterCard",
		PowerPerClick = 1,
		Price = 0,
		Level = 1,
		Color = Color3.fromRGB(105, 240, 255),
	},
	["Arc Pistol"] = {
		Id = "ArcPistol", CardName = "ArcCard",
		PowerPerClick = 5,
		Price = 150,
		Level = 2,
		Color = Color3.fromRGB(72, 136, 255),
	},
	["Tesla Rifle"] = {
		Id = "TeslaRifle", CardName = "TeslaCard",
		PowerPerClick = 15, Price = 600, Level = 5,
		Color = Color3.fromRGB(72, 218, 255),
	},
	["Storm Blaster"] = {
		Id = "StormBlaster", CardName = "StormCard",
		PowerPerClick = 40, Price = 2200, Level = 10,
		Color = Color3.fromRGB(218, 244, 255),
	},
	["Nuclear Conductor"] = {
		Id = "NuclearConductor", CardName = "NuclearCard",
		PowerPerClick = 100, Price = 8000, Level = 17,
		Color = Color3.fromRGB(132, 255, 81),
	},
	["Plasma Cannon"] = {
		Id = "PlasmaCannon", CardName = "PlasmaCard",
		PowerPerClick = 250, Price = 25000, Level = 25,
		Color = Color3.fromRGB(210, 103, 255),
	},
}
